spring:
  application:
    name: messaging-service

  datasource:
    url: jdbc:postgresql://localhost:5432/gophermarket
    username: gopher
    password: market123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: messaging

  flyway:
    enabled: true
    schemas: messaging
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8087
