spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/gophermarket
    username: gopher
    password: market123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: notifications

  flyway:
    enabled: true
    schemas: notifications
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8089
